package hr.fer.zemris.java.hw03.prob1;

import java.util.Objects;

/**
 * A token generated by {@link Lexer}.
 *
 * @author Marko Lazarić
 *
 */
public class Token {

	/**
	 * The type of the token.
	 */
	private final TokenType type;

	/**
	 * The value of the token.
	 */
	private final Object value;

	/**
	 * Constructs a new token with the given type and value.
	 *
	 * @param type the type of the token
	 * @param value the value of the token
	 *
	 * @throws NullPointerException if {@code type} is {@code null}
	 */
	public Token(TokenType type, Object value) {
		this.type = Objects.requireNonNull(type, "Type of token cannot be null.");
		this.value = value;
	}

	/**
	 * Returns the value of the token.
	 *
	 * @return the value of the token
	 */
	public Object getValue() {
		return value;
	}

	/**
	 * Returns the type of the token.
	 *
	 * @return the type of the token
	 */
	public TokenType getType() {
		return type;
	}
}