package hr.fer.zemris.java.custom.scripting.tokens;

/**
 * Types of tokens generated by {@link Lexer}.
 *
 * @author Marko Lazarić
 *
 */
public enum TokenType {

	/**
	 * End of file token. Represents the end of the input data.
	 *
	 * The value of a token of this type should be {@code null}.
	 */
	EOF,

	/**
	 * Represents a single word in the {@link LexerState#BASIC} state
	 * or a collection of words in the {@link LexerState#EXTENDED} state.
	 *
	 * The value of a token of this type should be a {@link String}.
	 */
	WORD,

	/**
	 * Represents a number that fits into a long.
	 *
	 * The value of a token of this type should be a {@link Long}.
	 */
	NUMBER,

	/**
	 * Represents a single symbol.
	 *
	 * The value of a token of this type should be a {@link Character}.
	 */
	SYMBOL;
}
