package hr.fer.zemris.java.hw05.db.lexer;

/**
 * The types of token generated by {@link QueryLexer}.
 *
 * @author Marko Lazarić
 *
 */
public enum TokenType {
	/**
	 * Represents a word containing only letters.
	 */
	WORD,

	/**
	 * Represents a string enclosed in quotes.
	 */
	STRING,

	/**
	 * Represents an operator which is made of these characters: <, =, >, !.
	 */
	OPERATOR,

	/**
	 * Represents the end of input data.
	 */
	EOF;
}
